/*
FOOD_WAREHOUSE 테이블에서 경기도에 위치한 창고의 ID, 이름, 주소, 냉동시설 여부를 조회하는 SQL문 
- 냉동시설 여부가 NULL인 경우, 'N'으로 출력
- 결과는 창고 ID를 기준으로 오름차순 정렬
*/

/*KEY POINT
    1. CASE를 이용하는 방법: 조건문 (ORACLE에서는 DECODE) 
    2. IFNULL을 이용하는 방법: IFNULL(COLUMN_NAME, REPLACEMENT) AS COLUMN_NAME
    3. (추천) COALESCE(A,B,C,..): 특정 행의 세 COLUMN에서 NOT_NULL이 아닌 COLUMN 값을 제일 먼저 RETURN
*/

-- FREEZER_YN이 NULL인 경우 'N'이 NOT NULL이라 반환
SELECT WAREHOUSE_ID, 
    WAREHOUSE_NAME, 
    ADDRESS, 
    COALESCE(FREEZER_YN, 'N') AS FREEZER_YN
FROM FOOD_WAREHOUSE
WHERE ADDRESS LIKE '%경기%'
ORDER BY WAREHOUSE_ID ASC;

-- IFNULL을 이용한 방법
SELECT WAREHOUSE_ID, 
    WAREHOUSE_NAME, 
    ADDRESS, 
    IFNULL(FREEZER_YN, 'N') AS FREEZER_YN
FROM FOOD_WAREHOUSE
WHERE ADDRESS LIKE '%경기%'
ORDER BY WAREHOUSE_ID ASC;

-- CASE를 이용한 풀이
SELECT WAREHOUSE_ID, 
    WAREHOUSE_NAME, 
    ADDRESS, 
    CASE WHEN FREEZER_YN IS NULL THEN 'N' ELSE FREEZER_YN END AS FREEZER_YN
FROM FOOD_WAREHOUSE
WHERE ADDRESS LIKE '%경기%'
ORDER BY WAREHOUSE_ID ASC;